version: "3.9"
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/exec
    entrypoint: ["sh", "/exec/start-backend.sh"]
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/exec
    entrypoint: ["sh", "/exec/start-frontend.sh"]
